/** ISO 3166-1 numeric → alpha-2 mapping */
export const numericToAlpha2: Record<number, string> = {
  4: "AF", 8: "AL", 12: "DZ", 20: "AD", 24: "AO", 32: "AR", 36: "AU",
  40: "AT", 31: "AZ", 50: "BD", 56: "BE", 64: "BT", 68: "BO", 70: "BA",
  72: "BW", 76: "BR", 100: "BG", 104: "MM", 108: "BI", 116: "KH",
  120: "CM", 124: "CA", 140: "CF", 144: "LK", 152: "CL", 156: "CN",
  170: "CO", 178: "CG", 180: "CD", 188: "CR", 191: "HR", 192: "CU",
  196: "CY", 203: "CZ", 204: "BJ", 208: "DK", 214: "DO", 218: "EC",
  818: "EG", 222: "SV", 231: "ET", 233: "EE", 246: "FI", 250: "FR",
  266: "GA", 276: "DE", 288: "GH", 300: "GR", 320: "GT", 324: "GN",
  332: "HT", 340: "HN", 348: "HU", 356: "IN", 360: "ID", 364: "IR",
  368: "IQ", 372: "IE", 376: "IL", 380: "IT", 388: "JM", 392: "JP",
  400: "JO", 398: "KZ", 404: "KE", 408: "KP", 410: "KR", 414: "KW",
  418: "LA", 422: "LB", 430: "LR", 434: "LY", 440: "LT", 442: "LU",
  450: "MG", 454: "MW", 458: "MY", 466: "ML", 484: "MX", 496: "MN",
  504: "MA", 508: "MZ", 516: "NA", 524: "NP", 528: "NL",
  554: "NZ", 558: "NI", 562: "NE", 566: "NG", 578: "NO", 586: "PK",
  591: "PA", 598: "PG", 600: "PY", 604: "PE", 608: "PH", 616: "PL",
  620: "PT", 634: "QA", 642: "RO", 643: "RU", 646: "RW",
  682: "SA", 686: "SN", 694: "SL", 706: "SO", 710: "ZA", 724: "ES",
  729: "SD", 740: "SR", 752: "SE", 756: "CH", 760: "SY", 762: "TJ",
  764: "TH", 768: "TG", 780: "TT", 788: "TN", 792: "TR", 800: "UG",
  804: "UA", 784: "AE", 826: "GB", 840: "US", 858: "UY", 860: "UZ",
  862: "VE", 704: "VN", 887: "YE", 894: "ZM", 716: "ZW", 242: "FJ",
  834: "TZ", 732: "EH", 548: "VU", 90: "SB",
  44: "BS", 52: "BB", 84: "BZ", 96: "BN", 132: "CV", 174: "KM",
  212: "DM", 226: "GQ", 308: "GD", 624: "GW", 296: "KI", 428: "LV",
  462: "MV", 584: "MH", 480: "MU", 583: "FM", 498: "MD", 492: "MC",
  660: "AG", 670: "VC", 882: "WS", 674: "SM", 678: "ST", 690: "SC",
  776: "TO", 798: "TV", 659: "KN", 666: "PM",
  // Additional
  499: "ME", 688: "RS", 807: "MK", 268: "GE", 51: "AM",
  626: "TL", 728: "SS", 417: "KG", 795: "TM",
};

/** ISO alpha-2 → country name (display) */
export const alpha2ToName: Record<string, string> = {
  AF: "Afghanistan", AL: "Albania", DZ: "Algeria", AD: "Andorra",
  AO: "Angola", AR: "Argentina", AU: "Australia", AT: "Austria",
  AZ: "Azerbaijan", BD: "Bangladesh", BE: "Belgium", BT: "Bhutan",
  BO: "Bolivia", BA: "Bosnia and Herzegovina", BW: "Botswana",
  BR: "Brazil", BG: "Bulgaria", MM: "Myanmar", BI: "Burundi",
  KH: "Cambodia", CM: "Cameroon", CA: "Canada", CF: "Central African Republic",
  LK: "Sri Lanka", CL: "Chile", CN: "China", CO: "Colombia",
  CG: "Republic of the Congo", CD: "Democratic Republic of the Congo",
  CR: "Costa Rica", HR: "Croatia", CU: "Cuba", CY: "Cyprus",
  CZ: "Czech Republic", BJ: "Benin", DK: "Denmark", DO: "Dominican Republic",
  EC: "Ecuador", EG: "Egypt", SV: "El Salvador", ET: "Ethiopia",
  EE: "Estonia", FI: "Finland", FR: "France", GA: "Gabon", DE: "Germany",
  GH: "Ghana", GR: "Greece", GT: "Guatemala", GN: "Guinea",
  HT: "Haiti", HN: "Honduras", HU: "Hungary", IN: "India",
  ID: "Indonesia", IR: "Iran", IQ: "Iraq", IE: "Ireland",
  IL: "Israel", IT: "Italy", JM: "Jamaica", JP: "Japan",
  JO: "Jordan", KZ: "Kazakhstan", KE: "Kenya", KP: "North Korea",
  KR: "South Korea", KW: "Kuwait", LA: "Laos", LB: "Lebanon",
  LR: "Liberia", LY: "Libya", LT: "Lithuania", LU: "Luxembourg",
  MG: "Madagascar", MW: "Malawi", MY: "Malaysia", ML: "Mali",
  MX: "Mexico", MN: "Mongolia", MA: "Morocco", MZ: "Mozambique",
  NA: "Namibia", NP: "Nepal", NL: "Netherlands", NZ: "New Zealand",
  NI: "Nicaragua", NE: "Niger", NG: "Nigeria", NO: "Norway",
  PK: "Pakistan", PA: "Panama", PG: "Papua New Guinea", PY: "Paraguay",
  PE: "Peru", PH: "Philippines", PL: "Poland", PT: "Portugal",
  QA: "Qatar", RO: "Romania", RU: "Russia", RW: "Rwanda",
  SA: "Saudi Arabia", SN: "Senegal", SL: "Sierra Leone", SO: "Somalia",
  ZA: "South Africa", ES: "Spain", SD: "Sudan", SR: "Suriname",
  SE: "Sweden", CH: "Switzerland", SY: "Syria", TJ: "Tajikistan",
  TH: "Thailand", TG: "Togo", TT: "Trinidad and Tobago", TN: "Tunisia",
  TR: "Turkey", UG: "Uganda", UA: "Ukraine", AE: "United Arab Emirates",
  GB: "United Kingdom", US: "United States", UY: "Uruguay",
  UZ: "Uzbekistan", VE: "Venezuela", VN: "Vietnam", YE: "Yemen",
  ZM: "Zambia", ZW: "Zimbabwe", FJ: "Fiji", TZ: "Tanzania",
  EH: "Western Sahara", VU: "Vanuatu", SB: "Solomon Islands",
  KI: "Kiribati", MH: "Marshall Islands", FM: "Micronesia",
  TO: "Tonga", TV: "Tuvalu",
  BS: "Bahamas", BB: "Barbados", BZ: "Belize", BN: "Brunei",
  CV: "Cape Verde", KM: "Comoros", DM: "Dominica", GQ: "Equatorial Guinea",
  GD: "Grenada", GW: "Guinea-Bissau", LV: "Latvia", MV: "Maldives",
  MU: "Mauritius", MD: "Moldova", MC: "Monaco", SM: "San Marino",
  ST: "São Tomé and Príncipe", SC: "Seychelles", AG: "Antigua and Barbuda",
  VC: "Saint Vincent and the Grenadines", KN: "Saint Kitts and Nevis",
  LC: "Saint Lucia", TL: "Timor-Leste", SS: "South Sudan",
  ME: "Montenegro", RS: "Serbia", MK: "North Macedonia",
  GE: "Georgia", AM: "Armenia", KG: "Kyrgyzstan", TM: "Turkmenistan",
};

export function getAlpha2FromNumeric(numericId: number): string | undefined {
  return numericToAlpha2[numericId];
}

export function getCountryName(alpha2: string): string {
  return alpha2ToName[alpha2] ?? alpha2;
}
